### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [DmytroLopushanskyy/Social-Media-Monitoring#1]
Як Ви думаєте шукати тренди? Чіткості в описах не знайшов. Пошук по ключовим словам, тренди, аналіз тональності. Ваш колега подав в репозиторій вордівські файли. З діалогу в Teams я також не можу побачити що все ж таки буде робитися. "написати програму, яка визначатиме ставлення в мережі до тебе". 
Аналіз  тональності дописів в соціальних мережах?
Тема: ?

**Comment by anrom7** [comment]
Тут можна подивитися на сучасну архітектуру рішень по твітах https://www.aclweb.org/anthology/P19-3026.pdf Тут про ключові слова і твіттер https://www.aclweb.org/anthology/P15-2105.pdf  https://www.aclweb.org/anthology/P15-4006.pdf https://www.aclweb.org/anthology/P12-3003.pdf

**Comment by DmytroLopushanskyy** [comment]
Дякуємо за коментарі. Наша остаточна узгоджена тема: 
**Формування аналітики згадок ключових слів у соціальних мережах**

Аналіз тональності та пошук трендів, про який йшла мова на початку роботи, ми постараємося додати пізніше. Зараз проект аналізує дописи в Twitter та Telegram і показує статистику згадок на [цій веб-сторінці](https://newskitbot6.herokuapp.com/)
