### ISSUE TITLE
ДЗ2

### ISSUE THREAD

**Issue by anrom7** [DmytroLopushanskyy/Social-Media-Monitoring#2]
"база даних має досить малі обмеження по пам’яті" - так обмеження є чи немає?
дані можна описати детальніше
вимоги розписані+

**Comment by DmytroLopushanskyy** [comment]
Дякуємо за зауваження. Так, обмеження є, - 512 МБ. Оскільки поки що ми збираємо дані лише за останній тиждень і зводимо їх обсяг до мінімум, то нам цього ліміту вистачає. Ми зберігаємо в базі тільки числову статистику за минулі дні.  Натомість за останній день зберігаємо більш детальну інформацію з посиланнями та іншими метаданими.

Сторінку дз2 ми оновили і доповнили.
